//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://akxnet.com", ConfigurationName = "IServerDuplexContract", CallbackContract = typeof(IServerDuplexContractCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
public interface IServerDuplexContract
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://akxnet.com/IServerDuplexContract/SendMessage")]
    void SendMessage(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerDuplexContractCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://akxnet.com/IServerDuplexContract/SendMessageResponse")]
    void SendResponse(string response);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerDuplexContractChannel : IServerDuplexContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerDuplexContractClient : System.ServiceModel.DuplexClientBase<IServerDuplexContract>, IServerDuplexContract
{

    public ServerDuplexContractClient(System.ServiceModel.InstanceContext callbackInstance) :
            base(callbackInstance)
    {
    }

    public ServerDuplexContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
            base(callbackInstance, endpointConfigurationName)
    {
    }

    public ServerDuplexContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ServerDuplexContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ServerDuplexContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, binding, remoteAddress)
    {
    }

    public void SendMessage(string message)
    {
        base.Channel.SendMessage(message);
    }
}
